---
- hosts: web
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    - include: tasks/firewall_httpd_default.yml
    - include: tasks/firewall.yml port=3206
    - include: tasks/firewall.yml port="{{ http_port }}"
