---
# ansible-playbook var_in_command.yml --extra-vars "hosts=web user=root"
# ansible-playbook var_in_command.yml --extra-vars "@vars.json"
# ansible-playbook var_in_command.yml --extra-vars "{'hosts':'vm-rhel7-1', 'user':'root'}"
- hosts: '{{ hosts }}'
  remote_user: '{{ user }}'

  tasks:
     - debug: msg="{{ hosts }}"
     - debug: msg="{{ user }}"
